name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Swift version
        run: swift --version
      - name: Build DocC
        run: |
          mkdir -p ./docs
          swift package \
            --allow-writing-to-directory ./docs \
            generate-documentation \
            --target ReleaseNotes \
            --output-path ./docs \
            --transform-for-static-hosting
      - name: Add root redirect
        run: |
          echo '<meta http-equiv="refresh" content="0; url=/documentation/releasenotes/">' > ./docs/index.html
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: gh-pages
          clean: true