name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Build DocC
        run: |
          swift package \
            --allow-writing-to-directory ./docs \
            generate-documentation \
            --target ReleaseNotes \
            --output-path ./docs \
            --transform-for-static-hosting \
            --hosting-base-path documentation/releasenotes

      - name: Add root redirect
        run: |
          echo '<meta http-equiv="refresh" content="0; url=/documentation/releasenotes/">' > ./docs/index.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: gh-pages
          clean: true
